# Form implementation generated from reading ui file 'UI/ui_dark_blue.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1616, 834)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color:#19232D;\n"
"}\n"
"QTextEdit {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QPlainTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QToolButton {\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(197, 197, 197), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(197, 197, 197));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QToolButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QPushButton::default{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(197, 197, 197), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(197, 197, 197));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-style: solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QLabel {\n"
"    color: #000000;\n"
"}\n"
"QLCDNumber {\n"
"    color: rgb(0, 113, 255, 255);\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(230, 230, 230);\n"
"    border-style: solid;\n"
"    background-color:rgb(207,207,207);\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"    border-radius: 10px;\n"
"}\n"
"QMenuBar {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(207, 209, 207, 255), stop:1 rgba(230, 229, 230, 255));\n"
"}\n"
"QMenuBar::item {\n"
"    color: #000000;\n"
"      spacing: 3px;\n"
"      padding: 1px 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(207, 209, 207, 255), stop:1 rgba(230, 229, 230, 255));\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu::item:selected {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    border-bottom-color: transparent;\n"
"    border-left-width: 2px;\n"
"    color: #000000;\n"
"    padding-left:15px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"}\n"
"QMenu::item {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    color: #000000;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#000000;\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(223,223,223);\n"
"        background-color:rgb(226,226,226);\n"
"        border-style: solid;\n"
"        border-width: 2px;\n"
"        border-radius: 6px;\n"
"}\n"
"QTabBar::tab:first {\n"
"    border-style: solid;\n"
"    border-left-width:1px;\n"
"    border-right-width:0px;\n"
"    border-top-width:1px;\n"
"    border-bottom-width:1px;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    color: #000000;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(247, 247, 247, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QTabBar::tab:last {\n"
"    border-style: solid;\n"
"    border-width:1px;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    color: #000000;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(247, 247, 247, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QTabBar::tab {\n"
"    border-style: solid;\n"
"    border-top-width:1px;\n"
"    border-bottom-width:1px;\n"
"    border-left-width:1px;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    color: #000000;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(247, 247, 247, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"      border-left-width:1px;\n"
"    border-right-color: transparent;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    color: #FFFFFF;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:first:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"      border-left-width:1px;\n"
"      border-bottom-width:1px;\n"
"      border-top-width:1px;\n"
"    border-right-color: transparent;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    color: #FFFFFF;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #000000;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: transparent;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #000000;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #000000;\n"
"}\n"
"QRadioButton {\n"
"    color: 000000;\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #a9b7c6;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"QSpinBox {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QDoubleSpinBox {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QTimeEdit {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QDateTimeEdit {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QDateEdit {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color:#000000;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color:#000000;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color:#000000;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color:#000000;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: rgb(181,181,181);\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: rgb(181,181,181);\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background-color: qlineargradient(spread:pad, y1:0.5, x1:1, y2:0.5, x2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"}\n"
"QScrollBar:horizontal {\n"
"    max-height: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    max-width: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(147, 200, 200);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(147, 200, 200);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"   border: 2px transparent grey;\n"
"   border-top-right-radius: 7px;\n"
"   border-bottom-right-radius: 7px;\n"
"   background: rgba(34, 142, 255, 255);\n"
"   width: 20px;\n"
"   subcontrol-position: right;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-right-radius: 7px;\n"
"   border-bottom-right-radius: 7px;\n"
"   background: rgb(181,181,181);\n"
"   width: 20px;\n"
"   subcontrol-position: right;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"   border: 2px transparent grey;\n"
"   border-bottom-left-radius: 7px;\n"
"   border-bottom-right-radius: 7px;\n"
"   background: rgba(34, 142, 255, 255);\n"
"   height: 20px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-bottom-left-radius: 7px;\n"
"   border-bottom-right-radius: 7px;\n"
"   background: rgb(181,181,181);\n"
"   height: 20px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 7px;\n"
"   border-bottom-left-radius: 7px;\n"
"   background: rgba(34, 142, 255, 255);\n"
"   width: 20px;\n"
"   subcontrol-position: left;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 7px;\n"
"   border-bottom-left-radius: 7px;\n"
"   background: rgb(181,181,181);\n"
"   width: 20px;\n"
"   subcontrol-position: left;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 7px;\n"
"   border-top-right-radius: 7px;\n"
"   background: rgba(34, 142, 255, 255);\n"
"   height: 20px;\n"
"   subcontrol-position: top;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 7px;\n"
"   border-top-right-radius: 7px;\n"
"   background: rgb(181,181,181);\n"
"   height: 20px;\n"
"   subcontrol-position: top;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"   border: 1px transparent grey;\n"
"   border-top-left-radius: 3px;\n"
"   border-bottom-left-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"   border: 1px transparent grey;\n"
"   border-top-right-radius: 3px;\n"
"   border-bottom-right-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"   border: 1px transparent grey;\n"
"   border-top-left-radius: 3px;\n"
"   border-top-right-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"   border: 1px transparent grey;\n"
"   border-bottom-left-radius: 3px;\n"
"   border-bottom-right-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"   background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"   background: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.image1Cmbx = QtWidgets.QComboBox(parent=self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        self.image1Cmbx.setFont(font)
        self.image1Cmbx.setStyleSheet("color: #19232D;")
        self.image1Cmbx.setProperty("image", 1)
        self.image1Cmbx.setObjectName("image1Cmbx")
        self.image1Cmbx.addItem("")
        self.image1Cmbx.addItem("")
        self.image1Cmbx.addItem("")
        self.image1Cmbx.addItem("")
        self.horizontalLayout_2.addWidget(self.image1Cmbx)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.imageOneOrigin = ImageView(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageOneOrigin.sizePolicy().hasHeightForWidth())
        self.imageOneOrigin.setSizePolicy(sizePolicy)
        self.imageOneOrigin.setMinimumSize(QtCore.QSize(313, 165))
        self.imageOneOrigin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.imageOneOrigin.setSizeIncrement(QtCore.QSize(0, 0))
        self.imageOneOrigin.setStyleSheet("background-color: #19232D; \n"
"color: rgb(0, 0, 0);")
        self.imageOneOrigin.setObjectName("imageOneOrigin")
        self.horizontalLayout.addWidget(self.imageOneOrigin)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.ResetBtn = QtWidgets.QPushButton(parent=self.groupBox)
        self.ResetBtn.setMinimumSize(QtCore.QSize(20, 0))
        self.ResetBtn.setStyleSheet("color: rgb(0, 0, 0);")
        self.ResetBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icons8-restart-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ResetBtn.setIcon(icon)
        self.ResetBtn.setIconSize(QtCore.QSize(16, 16))
        self.ResetBtn.setObjectName("ResetBtn")
        self.verticalLayout.addWidget(self.ResetBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.imageOneOrigin_2 = ImageView(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageOneOrigin_2.sizePolicy().hasHeightForWidth())
        self.imageOneOrigin_2.setSizePolicy(sizePolicy)
        self.imageOneOrigin_2.setMinimumSize(QtCore.QSize(313, 159))
        self.imageOneOrigin_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.imageOneOrigin_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.imageOneOrigin_2.setStyleSheet("background-color:#19232D;")
        self.imageOneOrigin_2.setObjectName("imageOneOrigin_2")
        self.horizontalLayout.addWidget(self.imageOneOrigin_2)
        self.checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_10.addWidget(self.groupBox)
        self.groupBox_7 = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.image3Cmbx = QtWidgets.QComboBox(parent=self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        self.image3Cmbx.setFont(font)
        self.image3Cmbx.setStyleSheet("color: rgb(25, 35, 45);")
        self.image3Cmbx.setProperty("image", 1)
        self.image3Cmbx.setObjectName("image3Cmbx")
        self.image3Cmbx.addItem("")
        self.image3Cmbx.addItem("")
        self.image3Cmbx.addItem("")
        self.image3Cmbx.addItem("")
        self.horizontalLayout_13.addWidget(self.image3Cmbx)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.imageThreeOrigin = ImageView(parent=self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageThreeOrigin.sizePolicy().hasHeightForWidth())
        self.imageThreeOrigin.setSizePolicy(sizePolicy)
        self.imageThreeOrigin.setMinimumSize(QtCore.QSize(313, 140))
        self.imageThreeOrigin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.imageThreeOrigin.setSizeIncrement(QtCore.QSize(0, 0))
        self.imageThreeOrigin.setStyleSheet("background-color:#19232D;\n"
"\\color: rgb(0, 0, 0);")
        self.imageThreeOrigin.setObjectName("imageThreeOrigin")
        self.horizontalLayout_14.addWidget(self.imageThreeOrigin)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.ResetBtn_3 = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.ResetBtn_3.setMinimumSize(QtCore.QSize(32, 0))
        self.ResetBtn_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.ResetBtn_3.setText("")
        self.ResetBtn_3.setIcon(icon)
        self.ResetBtn_3.setIconSize(QtCore.QSize(16, 16))
        self.ResetBtn_3.setObjectName("ResetBtn_3")
        self.verticalLayout_6.addWidget(self.ResetBtn_3)
        self.horizontalLayout_14.addLayout(self.verticalLayout_6)
        self.imageThreeOrigin_2 = ImageView(parent=self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageThreeOrigin_2.sizePolicy().hasHeightForWidth())
        self.imageThreeOrigin_2.setSizePolicy(sizePolicy)
        self.imageThreeOrigin_2.setMinimumSize(QtCore.QSize(313, 159))
        self.imageThreeOrigin_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.imageThreeOrigin_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.imageThreeOrigin_2.setStyleSheet("background-color:#19232D;")
        self.imageThreeOrigin_2.setObjectName("imageThreeOrigin_2")
        self.horizontalLayout_14.addWidget(self.imageThreeOrigin_2)
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_14.addWidget(self.checkBox_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_10.addWidget(self.groupBox_7)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.image2Cmbx = QtWidgets.QComboBox(parent=self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        self.image2Cmbx.setFont(font)
        self.image2Cmbx.setStyleSheet("color: rgb(25, 35, 45);")
        self.image2Cmbx.setProperty("image", 1)
        self.image2Cmbx.setObjectName("image2Cmbx")
        self.image2Cmbx.addItem("")
        self.image2Cmbx.addItem("")
        self.image2Cmbx.addItem("")
        self.image2Cmbx.addItem("")
        self.horizontalLayout_4.addWidget(self.image2Cmbx)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.imageTwoOrigin = ImageView(parent=self.groupBox_3)
        self.imageTwoOrigin.setMinimumSize(QtCore.QSize(313, 165))
        self.imageTwoOrigin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.imageTwoOrigin.setSizeIncrement(QtCore.QSize(0, 0))
        self.imageTwoOrigin.setStyleSheet("background-color:#19232D;\n"
"\\color: rgb(0, 0, 0);")
        self.imageTwoOrigin.setObjectName("imageTwoOrigin")
        self.horizontalLayout_3.addWidget(self.imageTwoOrigin)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.ResetBtn_2 = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.ResetBtn_2.setMinimumSize(QtCore.QSize(20, 0))
        self.ResetBtn_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.ResetBtn_2.setText("")
        self.ResetBtn_2.setIcon(icon)
        self.ResetBtn_2.setIconSize(QtCore.QSize(16, 16))
        self.ResetBtn_2.setObjectName("ResetBtn_2")
        self.verticalLayout_2.addWidget(self.ResetBtn_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.imageTwoOrigin_2 = ImageView(parent=self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageTwoOrigin_2.sizePolicy().hasHeightForWidth())
        self.imageTwoOrigin_2.setSizePolicy(sizePolicy)
        self.imageTwoOrigin_2.setMinimumSize(QtCore.QSize(313, 159))
        self.imageTwoOrigin_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.imageTwoOrigin_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.imageTwoOrigin_2.setStyleSheet("background-color:#19232D;")
        self.imageTwoOrigin_2.setObjectName("imageTwoOrigin_2")
        self.horizontalLayout_3.addWidget(self.imageTwoOrigin_2)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_3.addWidget(self.checkBox_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11.addWidget(self.groupBox_3)
        self.groupBox_8 = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem9)
        self.image4Cmbx = QtWidgets.QComboBox(parent=self.groupBox_8)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        self.image4Cmbx.setFont(font)
        self.image4Cmbx.setStyleSheet("color: rgb(0, 0, 0);")
        self.image4Cmbx.setProperty("image", 1)
        self.image4Cmbx.setObjectName("image4Cmbx")
        self.image4Cmbx.addItem("")
        self.image4Cmbx.addItem("")
        self.image4Cmbx.addItem("")
        self.image4Cmbx.addItem("")
        self.horizontalLayout_15.addWidget(self.image4Cmbx)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem10)
        self.imageFourOrigin = ImageView(parent=self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageFourOrigin.sizePolicy().hasHeightForWidth())
        self.imageFourOrigin.setSizePolicy(sizePolicy)
        self.imageFourOrigin.setMinimumSize(QtCore.QSize(313, 165))
        self.imageFourOrigin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.imageFourOrigin.setSizeIncrement(QtCore.QSize(0, 0))
        self.imageFourOrigin.setStyleSheet("background-color:#19232D;\n"
"\\color: rgb(0, 0, 0);")
        self.imageFourOrigin.setObjectName("imageFourOrigin")
        self.horizontalLayout_16.addWidget(self.imageFourOrigin)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem11)
        self.ResetBtn_4 = QtWidgets.QPushButton(parent=self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetBtn_4.sizePolicy().hasHeightForWidth())
        self.ResetBtn_4.setSizePolicy(sizePolicy)
        self.ResetBtn_4.setMinimumSize(QtCore.QSize(20, 0))
        self.ResetBtn_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.ResetBtn_4.setText("")
        self.ResetBtn_4.setIcon(icon)
        self.ResetBtn_4.setIconSize(QtCore.QSize(16, 16))
        self.ResetBtn_4.setObjectName("ResetBtn_4")
        self.verticalLayout_12.addWidget(self.ResetBtn_4)
        self.horizontalLayout_16.addLayout(self.verticalLayout_12)
        self.imageFourOrigin_2 = ImageView(parent=self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageFourOrigin_2.sizePolicy().hasHeightForWidth())
        self.imageFourOrigin_2.setSizePolicy(sizePolicy)
        self.imageFourOrigin_2.setMinimumSize(QtCore.QSize(313, 165))
        self.imageFourOrigin_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.imageFourOrigin_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.imageFourOrigin_2.setStyleSheet("background-color:#19232D;")
        self.imageFourOrigin_2.setObjectName("imageFourOrigin_2")
        self.horizontalLayout_16.addWidget(self.imageFourOrigin_2)
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_16.addWidget(self.checkBox_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_11.addWidget(self.groupBox_8)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.verticalLayout_13.addLayout(self.verticalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem14)
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioButton_ri = QtWidgets.QRadioButton(parent=self.groupBox_5)
        self.radioButton_ri.setGeometry(QtCore.QRect(0, 20, 116, 22))
        font = QtGui.QFont()
        font.setFamily(".Al Bayan PUA")
        font.setItalic(True)
        self.radioButton_ri.setFont(font)
        self.radioButton_ri.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_ri.setObjectName("radioButton_ri")
        self.radioButton_mp = QtWidgets.QRadioButton(parent=self.groupBox_5)
        self.radioButton_mp.setGeometry(QtCore.QRect(90, 20, 140, 22))
        font = QtGui.QFont()
        font.setFamily(".Al Bayan PUA")
        font.setItalic(True)
        self.radioButton_mp.setFont(font)
        self.radioButton_mp.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_mp.setObjectName("radioButton_mp")
        self.horizontalLayout_6.addWidget(self.groupBox_5)
        self.mixerOutput = QtWidgets.QComboBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.mixerOutput.setFont(font)
        self.mixerOutput.setAutoFillBackground(False)
        self.mixerOutput.setObjectName("mixerOutput")
        self.mixerOutput.addItem("")
        self.mixerOutput.addItem("")
        self.horizontalLayout_6.addWidget(self.mixerOutput)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.slider4_1 = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider4_1.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider4_1.setObjectName("slider4_1")
        self.gridLayout_4.addWidget(self.slider4_1, 0, 2, 1, 1)
        self.label_real_mag_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_real_mag_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_real_mag_4.setObjectName("label_real_mag_4")
        self.gridLayout_4.addWidget(self.label_real_mag_4, 0, 1, 1, 1)
        self.label_img_phase_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_img_phase_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_img_phase_4.setObjectName("label_img_phase_4")
        self.gridLayout_4.addWidget(self.label_img_phase_4, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.slider4_2 = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider4_2.setMinimum(0)
        self.slider4_2.setMaximum(10)
        self.slider4_2.setPageStep(1)
        self.slider4_2.setProperty("value", 9)
        self.slider4_2.setSliderPosition(9)
        self.slider4_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider4_2.setObjectName("slider4_2")
        self.gridLayout_4.addWidget(self.slider4_2, 1, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 3, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.slider2_2 = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider2_2.setMinimum(0)
        self.slider2_2.setMaximum(10)
        self.slider2_2.setPageStep(1)
        self.slider2_2.setProperty("value", 9)
        self.slider2_2.setSliderPosition(9)
        self.slider2_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider2_2.setObjectName("slider2_2")
        self.gridLayout_2.addWidget(self.slider2_2, 1, 2, 1, 1)
        self.slider2_1 = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider2_1.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider2_1.setObjectName("slider2_1")
        self.gridLayout_2.addWidget(self.slider2_1, 0, 2, 1, 1)
        self.label_real_mag_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_real_mag_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_real_mag_2.setObjectName("label_real_mag_2")
        self.gridLayout_2.addWidget(self.label_real_mag_2, 0, 1, 1, 1)
        self.label_img_phase_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_img_phase_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_img_phase_2.setObjectName("label_img_phase_2")
        self.gridLayout_2.addWidget(self.label_img_phase_2, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 3, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.slider3_1 = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider3_1.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider3_1.setObjectName("slider3_1")
        self.gridLayout_3.addWidget(self.slider3_1, 0, 2, 1, 1)
        self.slider3_2 = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider3_2.setMinimum(0)
        self.slider3_2.setMaximum(10)
        self.slider3_2.setPageStep(1)
        self.slider3_2.setProperty("value", 9)
        self.slider3_2.setSliderPosition(9)
        self.slider3_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider3_2.setObjectName("slider3_2")
        self.gridLayout_3.addWidget(self.slider3_2, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_real_mag_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_real_mag_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_real_mag_3.setObjectName("label_real_mag_3")
        self.gridLayout_3.addWidget(self.label_real_mag_3, 0, 1, 1, 1)
        self.label_img_phase_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_img_phase_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_img_phase_3.setObjectName("label_img_phase_3")
        self.gridLayout_3.addWidget(self.label_img_phase_3, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.slider1_2 = QtWidgets.QSlider(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider1_2.sizePolicy().hasHeightForWidth())
        self.slider1_2.setSizePolicy(sizePolicy)
        self.slider1_2.setMinimumSize(QtCore.QSize(200, 0))
        self.slider1_2.setMinimum(0)
        self.slider1_2.setMaximum(10)
        self.slider1_2.setPageStep(1)
        self.slider1_2.setProperty("value", 9)
        self.slider1_2.setSliderPosition(9)
        self.slider1_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider1_2.setObjectName("slider1_2")
        self.gridLayout.addWidget(self.slider1_2, 1, 2, 1, 1)
        self.slider1_1 = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider1_1.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider1_1.setObjectName("slider1_1")
        self.gridLayout.addWidget(self.slider1_1, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_real_mag_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_real_mag_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_real_mag_1.setObjectName("label_real_mag_1")
        self.gridLayout.addWidget(self.label_real_mag_1, 0, 1, 1, 1)
        self.label_img_phase_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_img_phase_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_img_phase_1.setObjectName("label_img_phase_1")
        self.gridLayout.addWidget(self.label_img_phase_1, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 1, 1, 2)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem16, 0, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.horizontalLayout_12.addLayout(self.verticalLayout_9)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem17)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.outputOne = ImageView(parent=self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(31)
        sizePolicy.setHeightForWidth(self.outputOne.sizePolicy().hasHeightForWidth())
        self.outputOne.setSizePolicy(sizePolicy)
        self.outputOne.setMinimumSize(QtCore.QSize(313, 165))
        self.outputOne.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.outputOne.setSizeIncrement(QtCore.QSize(0, 0))
        self.outputOne.setObjectName("outputOne")
        # self.progressBar = QtWidgets.QProgressBar(parent=self.outputOne)
        # self.progressBar.setGeometry(QtCore.QRect(10, 140, 141, 22))
        # self.progressBar.setProperty("value", 24)
        # self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_8.addWidget(self.outputOne)
        self.horizontalLayout_7.addWidget(self.groupBox_2)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.outputTwo = ImageView(parent=self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputTwo.sizePolicy().hasHeightForWidth())
        self.outputTwo.setSizePolicy(sizePolicy)
        self.outputTwo.setMinimumSize(QtCore.QSize(313, 165))
        self.outputTwo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.outputTwo.setSizeIncrement(QtCore.QSize(0, 0))
        self.outputTwo.setObjectName("outputTwo")
        # self.progressBar_2 = QtWidgets.QProgressBar(parent=self.outputTwo)
        # self.progressBar_2.setGeometry(QtCore.QRect(0, 140, 141, 22))
        # self.progressBar_2.setProperty("value", 24)
        # self.progressBar_2.setObjectName("progressBar_2")
        self.horizontalLayout_9.addWidget(self.outputTwo)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_7)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem18)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_22)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1616, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Image One"))
        self.image1Cmbx.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.image1Cmbx.setItemText(1, _translate("MainWindow", "Phase"))
        self.image1Cmbx.setItemText(2, _translate("MainWindow", "Real Component"))
        self.image1Cmbx.setItemText(3, _translate("MainWindow", "Imaginary Component"))
        self.imageOneOrigin.setToolTip(_translate("MainWindow", "press here to load the photo"))
        self.ResetBtn.setToolTip(_translate("MainWindow", "restart"))
        self.checkBox.setToolTip(_translate("MainWindow", "Enable ROI"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Image three"))
        self.image3Cmbx.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.image3Cmbx.setItemText(1, _translate("MainWindow", "Phase"))
        self.image3Cmbx.setItemText(2, _translate("MainWindow", "Real Component"))
        self.image3Cmbx.setItemText(3, _translate("MainWindow", "Imaginary Component"))
        self.imageThreeOrigin.setToolTip(_translate("MainWindow", "press here to load the photo"))
        self.ResetBtn_3.setToolTip(_translate("MainWindow", "restart"))
        self.checkBox_3.setToolTip(_translate("MainWindow", "Enable ROI"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Image Two"))
        self.image2Cmbx.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.image2Cmbx.setItemText(1, _translate("MainWindow", "Phase"))
        self.image2Cmbx.setItemText(2, _translate("MainWindow", "Real Component"))
        self.image2Cmbx.setItemText(3, _translate("MainWindow", "Imaginary Component"))
        self.imageTwoOrigin.setToolTip(_translate("MainWindow", "press here to load the photo"))
        self.ResetBtn_2.setToolTip(_translate("MainWindow", "restart"))
        self.checkBox_2.setToolTip(_translate("MainWindow", "Enable ROI"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Image Four"))
        self.image4Cmbx.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.image4Cmbx.setItemText(1, _translate("MainWindow", "Phase"))
        self.image4Cmbx.setItemText(2, _translate("MainWindow", "Real Component"))
        self.image4Cmbx.setItemText(3, _translate("MainWindow", "Imaginary Component"))
        self.imageFourOrigin.setToolTip(_translate("MainWindow", "press here to load the photo"))
        self.ResetBtn_4.setToolTip(_translate("MainWindow", "restart"))
        self.checkBox_4.setToolTip(_translate("MainWindow", "Enable ROI"))
        self.label_3.setText(_translate("MainWindow", "Mixer Output"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Mode"))
        self.radioButton_ri.setText(_translate("MainWindow", "Real/Img"))
        self.radioButton_mp.setText(_translate("MainWindow", "Mag/phase"))
        self.mixerOutput.setItemText(0, _translate("MainWindow", "Output 1"))
        self.mixerOutput.setItemText(1, _translate("MainWindow", "Output 2"))
        self.label_real_mag_4.setText(_translate("MainWindow", "mag"))
        self.label_img_phase_4.setText(_translate("MainWindow", "phase"))
        self.label_8.setText(_translate("MainWindow", "Image 4"))
        self.label.setText(_translate("MainWindow", "Image 2"))
        self.label_real_mag_2.setText(_translate("MainWindow", "mag"))
        self.label_img_phase_2.setText(_translate("MainWindow", "phase"))
        self.label_5.setText(_translate("MainWindow", "Image 3"))
        self.label_real_mag_3.setText(_translate("MainWindow", "mag"))
        self.label_img_phase_3.setText(_translate("MainWindow", "phase"))
        self.label_4.setText(_translate("MainWindow", "Image 1"))
        self.label_real_mag_1.setText(_translate("MainWindow", "mag"))
        self.label_img_phase_1.setText(_translate("MainWindow", "phase"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output One"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Output Two"))
        # roi in 1, 3, 5, 7
        self.images = [self.imageOneOrigin, self.imageTwoOrigin,
                       self.imageThreeOrigin, self.imageFourOrigin, self.imageOneOrigin_2, self.imageTwoOrigin_2,
                       self.imageThreeOrigin_2, self.imageFourOrigin_2
            , self.outputOne, self.outputTwo]
        self.rois = [
            (ROI([0, 0], [10, 10], rotatable=False, removable=True, maxBounds=QtCore.QRectF(0, 0, 313, 165)), i) for i
            in range(4)]

        self.image_items = []

        for widget in self.images:
            widget.ui.histogram.setFixedWidth(0)
            widget.ui.histogram.region.hide()
            widget.ui.histogram.vb.hide()
            widget.ui.histogram.axis.hide()
            widget.ui.histogram.gradient.hide()
            widget.ui.roiBtn.hide()
            widget.ui.menuBtn.hide()
            widget.ui.roiPlot.hide()

        for widget in self.images[:4] + self.images[8:]:
            widget.ui.histogram.gradient.setPos(0, 0)

        for widget in self.images[4:]:
            widget.ui.histogram.setFixedWidth(0)
            widget.ui.histogram.gradient.hide()

        for widget in self.images[:4]:
            widget.ui.histogram.setFixedWidth(0)

        # no brightness
        for index, widget in enumerate(self.images[4:8]):
            self.rois[index][0].addScaleHandle([1, 1], [0, 0])
            self.rois[index][0].addScaleHandle([0, 0], [1, 1])
            widget.getView().addItem(self.rois[index][0])

            imageItem = widget.getImageItem()
            self.image_items.append(imageItem)


from pyqtgraph import ImageView, ROI

